---
name: Unit test charts

on:
  pull_request:
  push:

jobs:
  unittest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.5.4

    - name: Run tests
      run: ./scripts/test-helm-unittest.sh
